### PR TITLE
Added compass initalization and started work on compass functions

### PR DESCRIPTION
**Pull request by richardshi97**
NOTE: Original functionality has not been altered yet.

### CODE REVIEW

**Comment by CoatedMoose** [comment]
Keep formatting consistent. If the decision is made to change the formatting conventions, submit a separate PR with only formatting changes.

**Comment by richardshi97** [comment]
Alright then, I'll try to revert the formatting first then add my team's new changes

**Comment by CoatedMoose** [comment]
Most IDE's let you configure tabs/space/size of indents. It is important to use consistent formatting so that the real (code + documentation) differences not get hidden by several hundred lines of whitespace changes.

**Comment by richardshi97** [comment]
Alright, tried to remove most of the extra formatting changes that were added by my IDE. Can't seem to remove the newline removals for some reason, not sure why.

**Pull request merged**
